name: video_toolset_io
description: "Video toolset IO"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    implements: video_toolset
    platforms:
      android:
        package: video_toolset
        pluginClass: VideoToolsetPlugin
        fileName: video_toolset_io.dart
      ios:
        pluginClass: VideoToolsetPlugin
        fileName: video_toolset_io.dart

dependencies:
  flutter:
    sdk: flutter
  video_toolset_platform_interface:
    git:
      url: https://github.com/jmp0x00/video_toolset.git
      path: video_toolset_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
