name: video_toolset_web
description: "Video toolset web"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    implements: video_toolset
    platforms:
      web:
        pluginClass: VideoToolsetPlugin
        fileName: video_toolset_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  video_toolset_platform_interface:
    path: ../video_toolset_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

