name: video_toolset
description: "Video Toolset"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: video_toolset_io
      ios:
        default_package: video_toolset_io
      web:
        default_package: video_toolset_web

dependencies:
  flutter:
    sdk: flutter
  video_toolset_platform_interface:
    git:
      url: https://github.com/jmp0x00/video_toolset.git
      path: video_toolset_platform_interface
  video_toolset_web:
    git:
      url: https://github.com/jmp0x00/video_toolset.git
      path: video_toolset_web
  video_toolset_io:
    git:
      url: https://github.com/jmp0x00/video_toolset.git
      path: video_toolset_io

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

